[2024-04-04 15:07:20,580] 96 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:80
 * Running on http://192.168.125.29:80
[2024-04-04 15:07:20,580] 96 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-04-04 15:07:37,336] 67 root - INFO - Dataframe Gathered
[2024-04-04 15:07:37,336] 53 root - INFO - Exception Occured in load_object function utils
[2024-04-04 15:07:37,336] 1414 app - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\src\FlightPricePrediction\utils\utils.py", line 50, in load_object
    with open(file_path,'rb') as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\src\FlightPricePrediction\pipelines\prediction_pipeline.py", line 18, in predict
    preprocessor=load_object(preprocessor_path)
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\src\FlightPricePrediction\utils\utils.py", line 54, in load_object
    raise customexception(e,sys)
src.FlightPricePrediction.exception.customexception: Error occured in python script name [C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\src\FlightPricePrediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 36, in predict_datapoint
    pred=predict_pipeline.predict(final_data)
  File "C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\src\FlightPricePrediction\pipelines\prediction_pipeline.py", line 30, in predict
    raise customexception(e,sys)
src.FlightPricePrediction.exception.customexception: Error occured in python script name [C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\src\FlightPricePrediction\pipelines\prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\vaibh\OneDrive\Desktop\Flight_Fare_Project\src\FlightPricePrediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'artifacts\\preprocessor.pkl']]
[2024-04-04 15:07:37,350] 96 werkzeug - INFO - 127.0.0.1 - - [04/Apr/2024 15:07:37] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
